### ISSUE TITLE
bill.sql raw_item_ts primary key should not be item_id

### ISSUE THREAD

**Issue by kevinliang43** [BU-NU-CLOUD-F19/MOC_Reporting#22]

**Comment by kevinliang43** [comment]
The change happened in this PR: https://github.com/BU-NU-CLOUD-F19/MOC_Reporting/pull/7/files

Before:
![image](https://user-images.githubusercontent.com/15353453/68028704-e68a7c80-fc8b-11e9-9446-1fdba62eba52.png)

Current:
![image](https://user-images.githubusercontent.com/15353453/68028725-f73af280-fc8b-11e9-8318-0f26b3ead756.png)

Currently, we cannot insert multiple rows for a single `item_id` as `item_id` is the primary key for the table.

**Comment by rob-baron** [comment]
Add the start_ts and end_ts to primary key.

The item_id needs to be there as a foreign key as there needs to be an item in the item table.
